frontend/controllers/ImageController.php
<?php
//! ЭТО НЕ КОНТРОЛЛЕР МОДЕЛИ IMAGE
namespace app\controllers;

use Yii;
use app\models\Product;
use rico\yii2images\models\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ImageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['setmain', 'deleteajax', 'sort'],
                'rules' => [
                    [
                        'actions' => ['setmain', 'deleteajax', 'sort'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
		return 1;
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteajax()
    {
		$request = Yii::$app->request->post();
		if (isset($request['id'])) {
			$id = $request['id'];
		} else {
			return false;
		}
		$image = Image::findOne($id);
		
		if($image) {
			$modelName = 'app\models\\'.$image->modelName;
			$modelId = $image->itemId;
			$model = new $modelName;
			$model = $model->findOne($modelId);
			$model->removeImage($image); return true;
		} else {
			return false;
		}
    }


    public function actionSetmain()
    {
		$request = Yii::$app->request->post();
		if (isset($request['id'])) {
			$id = $request['id'];
		} else {
			return false;
		}
		$image = Image::findOne($id);
		
		if($image) {
			$modelName = 'app\models\\'.$image->modelName;
			$modelId = $image->itemId;
			$model = new $modelName;
			$model = $model->findOne($modelId);
			$model->setMainImage($image); return true;
		} else {
			return false;
		}
    }
//! чет не работает
    public function actionLastimage()
    {
		$request = Yii::$app->request->post();
		if (isset($request['modelId'])) {
			$modelId = $request['modelId'];
		} else {
			return false;
		}
		$modelName = 'app\models\\'.'Product';
		$model = new $modelName;
		$model = $model->findOne($modelId);
		
		$images = $model->getImages();
		$image = array_pop($images);

		if($image) {
			return $this->actionSingle($image->id);
		} else {
			return false;
		}
    }

    public function actionSingle($id = null)
    {
		$request = Yii::$app->request->post();
		if (!$id && !isset($request['id'])) {
			return false;
		} else if (!$id && isset($request['id'])){
			$id = $request['id'];
		}
		$image = Image::findOne($id);
		
		if($image) {
            return $this->renderPartial('image-block', [
                'p_img' => $image,
            ]);
		} else {
			return false;
		}
    }

    public function actionSort()
    {
		$request = Yii::$app->request->post();
		if (!isset($request['new_order'])) {
			return false;
		}
		
		$new_order = $request['new_order'];
		$new_order = (array)explode('&', $new_order);
		if (!$new_order) return false;
		
		$j=1;
		foreach ($new_order as $i) {
			$image = Image::findOne($i);
			if ($image) {
				$image->setAttribute('sortOrder', $j);
				$image->save();
				$j++;
				unset($image);
			} else {
				return false;
			}
		}
		return true;
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    //! Сделать
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\models\ProductSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yz\shoppingcart\ShoppingCart;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller {
//! БИСТАФФ ВКЛЮЧИ ВАЛИДАЦИЮ.
  public $enableCsrfValidation = false;
  public function behaviors() {
    return [
      'verbs'  => [
        'class'   => VerbFilter::className(),
        'actions' => [
          'delete' => ['post'],
        ],
      ],
      'access' => [
        'class' => AccessControl::className(),
        'only'  => ['create', 'update', 'uploadimage', 'delete'],
        'rules' => [
          [
            'allow'   => true,
            'actions' => ['login', 'signup'],
            'roles'   => ['?'],
          ],
          [
            'allow'   => true,
            'actions' => ['create', 'update', 'uploadimage', 'delete'],
            'roles'   => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
   * Lists all Product models.
   * @return mixed
   */
  public function actionIndex() {
    $searchModel = new ProductSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('index', [
      'searchModel'  => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single Product model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id) {
    $model = $this->findModel($id);
    $categories = Category::find()
      ->joinWith('products', false)
      ->groupBy([Category::tablename() . '.id'])
      ->having('COUNT(' . Product::tablename() . '.id) > 3')
      ->asArray()
      ->all();

    foreach ($categories as &$c) {
      $c = ['label' => $c[Yii::t('site', 'description_en')], 'url' => ['category/view', 'id' => $c['id']], 'active' => ($model->category_id == $c['id']) ? true : null];
    }

    return $this->render('view', [
      'model'      => $model,
      'categories' => $categories,
    ]);
  }

  /**
   * Creates a new Product model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new Product();

    $get = Yii::$app->request->get();

    if (isset($get['category_id'])) {
      $model->load([
        'Product' => ['category_id' => $get['category_id']],
      ]);
    }

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('create', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing Product model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post())) {
      if ($model->validate()) {
        $model->save(false);

        return $this->redirect(['view', 'id' => $model->id]);
      }
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }
  }

  public function actionUploadimage($id) {
    $model = $this->findModel($id);
    $file = array_pop($_FILES);

    if (isset($file['tmp_name'])) {
      if (getimagesize($file['tmp_name'])) {
        rename($file['tmp_name'], $file['tmp_name'] . $file['name']);
        $model->attachImage($file['tmp_name'] . $file['name']);
        return true;
      }
    }

    return false;
  }

  /**
   * Deletes an existing Product model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }

  /**
   * Finds the Product model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Product the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = Product::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  public function actionAddtocart($id) {
    $cart = new ShoppingCart();

    $model = Product::findOne($id);

    if ($model) {
      $cart->put($model, 1);
      return $this->redirect(['view', 'id' => $model->id]);
    }

    throw new NotFoundHttpException();
  }

  public function actionBuyitnow($id) {
    $cart = new ShoppingCart();

    $model = Product::findOne($id);

    if ($model) {
      $cart->put($model, 1);
      return $this->redirect(['cart/view']);
    }

    throw new NotFoundHttpException();
  }
}

frontend/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\Product;
use rico\yii2images\models\Image;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;

class SiteController extends Controller {
  public function behaviors() {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only'  => ['logout'],
        'rules' => [
          [
            'actions' => ['logout'],
            'allow'   => true,
            'roles'   => ['@'],
          ],
        ],
      ],
      'verbs'  => [
        'class'   => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  public function actions() {
    return [
      'error'   => [
        'class' => 'yii\web\ErrorAction',
      ],
      'captcha' => [
        'class'           => 'yii\captcha\CaptchaAction',
        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
      ],
    ];
  }

  public function actionIndex() {
    $gal = new JustifiedGallery(['x' => '1140', 'y' => '640'], ['x' => '0', 'y' => '0']);
    $gal->cut();
    $ratios = $gal->getRatios();
    $count = count($ratios);
    $products = Product::find()->orderBy('RAND()')->limit($count)->all();
    $arr = array();

    foreach ($products as $p) {
      $arr[] = [
        'path' => $p->getImage()->getPath('500x500', ['fit' => true, 'abs' => true]),
        'href' => Url::to(['product/view', 'id' => $p->id]),
      ];
    }

    $gal->fillImages($arr);

    return $this->render('index', [
      'gal' => $gal,
    ]);
  }

  public function actionLogin() {
    if (!\Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();

    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    return $this->render('login', [
      'model' => $model,
    ]);
  }

  public function actionLogout() {
    Yii::$app->user->logout();

    return $this->goHome();
  }

  public function actionContact() {
    $model = new ContactForm();

    if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
      Yii::$app->session->setFlash('contactFormSubmitted');

      return $this->refresh();
    }

    return $this->render('contact', [
      'model' => $model,
    ]);
  }

  public function actionAbout() {
    return $this->render('about');
  }

  public function actionFurniture() {
    $categories = (new Category())->find()->asArray()->all();

    foreach ($categories as &$c) {
      $c = ['label' => $c[Yii::t('site', 'description_en')], 'url' => Url::to(['category/view', 'id' => $c['id']])];
    }

    return $this->redirect(['category/view', 'id' => 1]);

    return $this->render('furniture', [
      'categories' => $categories,
      'products'   => new ArrayDataProvider([
        'allModels'  => (new Product())->find()
          ->orderBy(['sort_order' => SORT_ASC])
        //->limit(20)
          ->all(),
        'pagination' => false,
      ]),
    ]);
  }

  public function actionTechnology() {
    return $this->render('technology');
  }
}

class JGSlice {
  public $size;
  public $offset;
  public $finaled = 0;
  public $ratio;
  public $next_cut;
  public function __construct($size, $offset, $next_cut = 'x') {
    $this->size = $size;
    $this->offset = $offset;
    $this->next_cut = $next_cut;
    $this->ratio = ($this->size['y'] > 0) ? $this->size['x'] / $this->size['y'] : 1000;
    return $this;
  }

  public function makeFinal() {
    $this->finaled = 1;
    return $this;
  }
}

class JustifiedGallery {
  public $size;
  public $minheight = 200;
  public $maxheight = 400;
  public $minwidth = 280;
  public $maxwidth = 550;
  public $minratio = 1.1;
  public $maxratio = 1.9;
  public $slices = array();

  public function __construct($size, $offset) {
    $this->size = $size;
    $this->offset = $offset;
    $this->slices[] = new JGSlice($size, $offset);
    return $this;
  }

  function cut() {
    $i = 0;

    while (isset($this->slices[$i]) && $i < 10000) {
      $slice = $this->slices[$i];

      if ($slice->next_cut == 'x') {
        $this->sliceVertical($slice, $i);
      } else {
        $this->sliceHorizontal($slice, $i);
      }

      ++$i;
    }

    return $this;
  }

  function sliceVertical($slice, $i) {
    $size = $slice->size;
    $offset = $slice->offset;

    if ($size['y'] < 2 * $this->minheight) {
      $margin = max([$size['y'] * $this->minratio, $this->minwidth]);
    } else {
      $margin = $this->minwidth;
    }

    if ($size['x'] < 2 * $margin) {
      if ($this->slices[$i]->ratio < $this->minratio) {
        $this->slices[] = new JGSlice($size, $offset, 'y');
        unset($this->slices[$i]);
      } else {
        $this->slices[$i]->makeFinal();
      }

      return $this;
    }

    $cut = rand($margin, $size['x'] - $margin - 1);
    $tmp = $size['x'];
    $size['x'] = $cut;
    $this->slices[] = new JGSlice($size, $offset, 'y');

    $offset['x'] += $size['x'];
    $size['x'] = $tmp - $size['x'];
    $this->slices[] = new JGSlice($size, $offset, 'y');
    unset($this->slices[$i]);
    return $this;
  }

  function sliceHorizontal($slice, $i) {
    $size = $slice->size;
    $offset = $slice->offset;

    if ($size['x'] < 2 * $this->minwidth) {
      $margin = max([$size['x'] / $this->maxratio, $this->minheight]);
    } else {
      $margin = $this->minheight;
    }

    if ($size['y'] < 2 * $margin) {
      if ($this->slices[$i]->ratio > $this->maxratio) {
        $this->slices[] = new JGSlice($size, $offset, 'x');
        unset($this->slices[$i]);
      } else {
        $this->slices[$i]->makeFinal();
      }

      return $this;
    }

    $cut = rand($margin, $size['y'] - $margin - 1);
    $tmp = $size['y'];
    $size['y'] = $cut;
    $this->slices[] = new JGSlice($size, $offset, 'x');

    $offset['y'] += $size['y'];
    $size['y'] = $tmp - $size['y'];
    $this->slices[] = new JGSlice($size, $offset, 'x');
    unset($this->slices[$i]);
    return $this;
  }

  public function getHtml() {
    $html = '<div style="position: relative; width:' . $this->size['x'] . 'px; height:' . $this->size['y'] . 'px;">';

    foreach ($this->slices as $s) {
      $html .= PHP_EOL . '<div style="padding: 5px; position: absolute; width:' . $s->size['x'] . 'px; height:' . $s->size['y'] . 'px; left:' . $s->offset['x'] . 'px; top:' . $s->offset['y'] . 'px;">'
      . '<a style="display: block; background-size:cover; background-position:center; width:100%; height:100%; background-image:url(\'' . ($s->image['path']) . '\')" href="' . $s->image['href'] . '"></a>'

        . '</div>';
    }

    $html .= '</div>';
    return $html;
  }

  public function getRatios() {
    $arr = array();

    foreach ($this->slices as $s) {
      $arr[] = $s->ratio;
    }

    return $arr;
  }

  public function getCount() {
    return count($this->getgetRatios());
  }

  public function fillImages($arr) {
    $i = 0;

    foreach ($this->slices as &$s) {
      $s->image = $arr[$i];
      ++$i;
    }

    return $this;
  }
}

frontend/views/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'model_ru') ?>

    <?= $form->field($model, 'model_en') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'quantity') ?>

    <?php // echo $form->field($model, 'length') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'weight') ?>

    <?php // echo $form->field($model, 'date_added') ?>

    <?php // echo $form->field($model, 'sort_order') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/product/images.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$product_images = $model->getImages();
$modelId = $model->id;
$uploadimageurl = Url::to(['product/uploadimage', 'id' => $model->id]);

$deleteimageajaxurl = Url::to(['image/deleteajax']);
$setmainimageurl = Url::to(['image/setmain']);
$singleimageurl = Url::to(['image/lastimage']);
$imagesorturl = Url::to(['image/sort']);

$js = <<<JS
var dropZone = $('#dropZone'),
    maxFileSize = 5000000; // максимальный размер фалйа - 1 мб.

// Проверка поддержки браузером
if (typeof(window.FileReader) == 'undefined') {
    dropZone.text('Не поддерживается браузером!');
    dropZone.addClass('error');
}

// Добавляем класс hover при наведении
dropZone[0].ondragover = function() {
    dropZone.addClass('hover');
    return false;
};

// Убираем класс hover
dropZone[0].ondragleave = function() {
    dropZone.removeClass('hover');
    return false;
};

// Обрабатываем событие Drop
dropZone[0].ondrop = function(event) {
    event.preventDefault();
    dropZone.removeClass('hover');
    dropZone.addClass('drop');
    
    var file;
    for (i = 0; i < event.dataTransfer.files.length; i++) {
		file = event.dataTransfer.files[i];
		
	    // Проверяем размер файла
	    if (file.size > maxFileSize) {
	        dropZone.text('Файл слишком большой!');
	        dropZone.addClass('error');
	        return false;
	    }
	    if(!file.type.match('image')){
	        dropZone.text('Не картинка!');
	        dropZone.addClass('error');
	        return false;
	    }
	    
	    // Создаем запрос
	    var formData = new FormData();
		formData.append(file.name, file);
	    var xhr = new XMLHttpRequest();
	    xhr.upload.addEventListener('progress', uploadProgress, false);
	    xhr.onreadystatechange = stateChange;
	    xhr.open('POST', '{$uploadimageurl}', true);
	    xhr.send(formData);
	}
};

// Показываем процент загрузки
function uploadProgress(event) {
    var percent = parseInt(event.loaded / event.total * 100);
    dropZone.text('Загрузка: ' + percent + '%');
}

// Пост обрабочик
function stateChange(event) {
    if (event.target.readyState == 4) {
        if (event.target.status == 200) {
	        if (event.target.response == true) {
	            dropZone.text('Загрузка успешно завершена!');
				$.ajax({
					method: 'POST',
					url: '$singleimageurl',
					data: {
						modelId: $modelId,
					},
					//! типа надо сделать, чтобы аплопдер возвращал айдишник загруженной фотки и запрашивать фотку по айдишнику, а то визникает ошибка, когда много фоток грузишь
					success: function(response) {
						if(response) {
							$('#dropZone').before(response);
							$('.product-update .product-images').sortable('refresh');
						}
					}
				});
	        } else {
	            dropZone.text('Это не картинка?!');
	            dropZone.addClass('error');
	        }
        } else {
            dropZone.text('Произошла ошибка!');
            dropZone.addClass('error');
        }
    }
}

$('.product-update .product-images').sortable({
	items: ".product-image:not(.main-image, #dropZone)",
	opacity: 0.5,
	revert: 100,
	containment: ".product-images",
	placeholder: 'ui-state-highlight',
	tolerance: "pointer",
	stop: function( event, ui ) {
		var res = $('.product-update .product-images').sortable("serialize", {key: "data-image-id"});
		res = res.replace(/data-image-id=/g,'');

		$.ajax({
			method: 'POST',
			url: '$imagesorturl',
			data: {
				new_order: res,
			},
			success: function(response) {
				if (response == true) {
					$('.product-update .product-images').sortable
				}
			}
		});
	}
});
JS;
$this->registerJs($js);

$js= <<<JS
function deleteImage(id) {
	if (confirm('Удалить?')) {
		$.ajax({
			method: 'POST',
			url: '$deleteimageajaxurl',
			data: {
				id: id,
			},
			success: function(response) {
				if(response == true) {
					$('#image-block-' + id).remove();
				}
			}
		});
	}
}
function setMainImage(id) {
	$.ajax({
		method: 'POST',
		url: '$setmainimageurl',
		data: {
			id: id,
		},
		success: function(response) {
			if(response == true) {
				$('.main-image.product-image').removeClass('main-image');
				$('#image-block-' + id).addClass('main-image');
				$('.product-update .product-images').prepend($('.product-update .product-images .main-image'));
				$('.product-update .product-images').sortable('refresh');
			}
		}
	});
}
JS;
$this->registerJs($js, yii\web\View::POS_END, null);

?>

<?php if ($product_images) foreach ($product_images as $p_img) {
	echo $this->render('/image/image-block', [ 'p_img' => $p_img ]);
} ?>
<div id="dropZone" class="product-image text-center" style="">
	СЮДА
</div>

frontend/views/product/view.php
<?php

  use app\widgets\ProductDescription;
  use app\widgets\ProductDimensions;
  use yii\helpers\Html;
  use yii\helpers\Url;
  use yii\widgets\Breadcrumbs;
  use yii\widgets\DetailView;

  /* @var $this yii\web\View */
  /* @var $model app\models\Product */

  $this->title = $model->{Yii::t('site', 'model_en')};
  $category = $model->getCategory()->one();
  $this->params['breadcrumbs'][] = ['label' => Yii::t('site', 'Catalog'), 'url' => ['site/furniture']];
  $this->params['breadcrumbs'][] = ['label' => $category->{Yii::t('site', 'description_en')}, 'url' => ['category/view', 'id' => $category->id]];

  if (count($categories) > 1) {
    $this->params['secondary_nav_items'] = $categories;
  }

  $product_images = $model->getImages();

  $js = <<<JS

  function resizeProductGal() {
    $('.product-images').css({
      'height': Math.max($(window).height() - $('.les-navbar').outerHeight() - $('footer').outerHeight() - 45, $('.product-description').outerHeight(), 700),
      'overflow-y': 'scroll'
    });

  };
  resizeProductGal();
  $(window).on('resize', function(){
    resizeProductGal();
  });
  $("a.single_image").fancybox();
JS;
  $this->registerJsFile('/js/jquery.elevateZoom-3.0.8.min.js', ['depends' => 'app\assets\AppAsset']);
  $this->registerJsFile('/js/fancybox/jquery.fancybox.pack.js', ['depends' => 'app\assets\AppAsset']);
  $this->registerCssFile('/js/fancybox/jquery.fancybox.css');
  $this->registerJs($js);

?>
<div class="product-view row clearfix">
  <div class="col-xs-6 product-images">
      <ul>
    <?php

      if ($product_images) {
      foreach ($product_images as $p_img) {?>
          <li>
            <a class="single_image" href="/<?=$p_img->getPath()?>">
              <img class="product-image" src="<?=$p_img->getPath('555x', ['abs' => true])?>" alt="<?=$model->sku_ru?>" data-orig-src="<?=$p_img->getPath('555x', ['abs' => true])?>" style="width:100%;"/>
            </a>
          </li>
    <?php }
      }

    ?>
      </ul>
  </div>
  <div class="col-xs-6 product-description" style="padding-left:30px;">
        <?=Breadcrumbs::widget([
  'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
])?>
    <div class="description">
      <div class="title space-bottom-medium">
        <h2 class="text-uppercase"><?=$model->{Yii::t('site', 'model_en')}?></h2>
      </div>
      <div class="product-description">
        <?=ProductDescription::widget(['model' => $model])?>
      </div>

      <div class="specs">
        <div class="spec">
          <h3 class="text-uppercase"><?=Yii::t('site', 'Size')?></h3>
          <span class="size text-grey">
            <?=ProductDimensions::widget(['model' => $model])?>
          </span>
        </div>

        <div class="spec">
          <h3 class="text-uppercase"><?=Yii::t('site', 'Price')?></h3>
          <span class="price text-grey"><?=$model->price?> <span class="glyphicon glyphicon-ruble" style="font-size:11px;"/>.</span>
          &#x20;- <?=$model->status->{Yii::t('site', 'description_en')}?>
        </div>
      </div>

      <div class="cart-actions">
        <div class="action add-co-cart col-xs-6">
          <a class="text-center" href="<?=URL::to(['product/addtocart', 'id' => $model->id])?>"><?=Yii::t('site', 'Add to cart')?></a>
        </div>
        <div class="action buy-it-now col-xs-6">
          <a class="text-center" href="<?=URL::to(['product/buyitnow', 'id' => $model->id])?>"><?=Yii::t('site', 'Place an order')?></a>
        </div>
      </div>

    </div>
  </div>
</div>


<?php

if (!Yii::$app->user->isGuest): ?>

    <h1><?=Html::encode($this->title)?></h1>

    <p>
        <?=Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary'])?>
        <?=Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
  'class' => 'btn btn-danger',
  'data'  => [
    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
    'method'  => 'post',
  ],
])?>
    </p>

    <?=DetailView::widget([
  'model'      => $model,
  'attributes' => [
    'id',
    'model_ru',
    'model_en',
    'sku_ru',
    'sku_en',
    'category.' . Yii::t('site', 'description_en'),
    'material.' . Yii::t('site', 'description_en'),
    'cut.' . Yii::t('site', 'description_en'),
    'price',
    'quantity',
    'length',
    'width_floor',
    'width_ceil',
    'height',
    // 'date_added:datetime',
    'sort_order',
  ],
])?>
<?php endif;?>