frontend/models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%categories}}".
 *
 * @property integer $id
 * @property string $description_ru
 * @property string $description_en
 */
class Category extends \yii\db\ActiveRecord {
  /**
   * @inheritdoc
   */
  public static function tableName() {
    return '{{%categories}}';
  }

  /**
   * @inheritdoc
   */
  public function rules() {
    return [
      [['description_ru', 'description_en'], 'string', 'max' => 32],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels() {
    return [
      'id'             => Yii::t('app', 'ID'),
      'description_ru' => Yii::t('site', 'Category'),
      'description_en' => Yii::t('site', 'Category'),
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getProducts() {
    return $this->hasMany(Product::className(), ['category_id' => 'id']);
  }
}

frontend/controllers/CategoryController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\models\ProductFilter;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller {
  public function behaviors() {
    return [
      'verbs'  => [
        'class'   => VerbFilter::className(),
        'actions' => [
          'delete' => ['post'],
        ],
      ],
      'access' => [
        'class' => AccessControl::className(),
        'only'  => ['create', 'update', 'index', 'delete'],
        'rules' => [
          [
            'allow'   => true,
            'actions' => ['login', 'signup'],
            'roles'   => ['?'],
          ],
          [
            'allow'   => true,
            'actions' => ['create', 'update', 'index', 'delete'],
            'roles'   => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
   * Lists all Category models.
   * @return mixed
   */
  public function actionIndex() {
    $dataProvider = new ActiveDataProvider([
      'query' => Category::find(),
    ]);

    return $this->render('index', [
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single Category model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id) {
    $categories = Category::find()
      ->joinWith('products', false)
      ->groupBy([Category::tablename() . '.id'])
      ->having('COUNT(' . Product::tablename() . '.id) > 3')
      ->asArray()
      ->all();

    if (count($categories) == 1 && $id != $categories[0]['id']) {
      return $this->redirect(['category/view', 'id' => $categories[0]['id']]);
    }

    foreach ($categories as &$c) {
      $c = ['label' => $c[Yii::t('site', 'description_en')], 'url' => ['category/view', 'id' => $c['id']]];
    }

    $model = $this->findModel($id);
    $filter = new ProductFilter(['category_id' => $id]);
    $filter->load(Yii::$app->request->get());
    $dataProvider = $filter->search();
    $dataProvider->pagination = false;

    return $this->render('view', [
      'model'      => $model,
      'categories' => $categories,
      'filter'     => $filter,
      'products'   => $dataProvider,
    ]);
  }

  /**
   * Creates a new Category model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new Category();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('create', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing Category model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Deletes an existing Category model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }

  /**
   * Finds the Category model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Category the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = Category::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }
}

frontend/controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\models\ProductSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yz\shoppingcart\ShoppingCart;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller {
//! БИСТАФФ ВКЛЮЧИ ВАЛИДАЦИЮ.
  public $enableCsrfValidation = false;
  public function behaviors() {
    return [
      'verbs'  => [
        'class'   => VerbFilter::className(),
        'actions' => [
          'delete' => ['post'],
        ],
      ],
      'access' => [
        'class' => AccessControl::className(),
        'only'  => ['create', 'update', 'uploadimage', 'delete'],
        'rules' => [
          [
            'allow'   => true,
            'actions' => ['login', 'signup'],
            'roles'   => ['?'],
          ],
          [
            'allow'   => true,
            'actions' => ['create', 'update', 'uploadimage', 'delete'],
            'roles'   => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
   * Lists all Product models.
   * @return mixed
   */
  public function actionIndex() {
    $searchModel = new ProductSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('index', [
      'searchModel'  => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single Product model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id) {
    $model = $this->findModel($id);
    $categories = Category::find()
      ->joinWith('products', false)
      ->groupBy([Category::tablename() . '.id'])
      ->having('COUNT(' . Product::tablename() . '.id) > 3')
      ->asArray()
      ->all();

    foreach ($categories as &$c) {
      $c = ['label' => $c[Yii::t('site', 'description_en')], 'url' => ['category/view', 'id' => $c['id']], 'active' => ($model->category_id == $c['id']) ? true : null];
    }

    return $this->render('view', [
      'model'      => $model,
      'categories' => $categories,
    ]);
  }

  /**
   * Creates a new Product model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new Product();

    $get = Yii::$app->request->get();

    if (isset($get['category_id'])) {
      $model->load([
        'Product' => ['category_id' => $get['category_id']],
      ]);
    }

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('create', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing Product model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post())) {
      if ($model->validate()) {
        $model->save(false);

        return $this->redirect(['view', 'id' => $model->id]);
      }
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }
  }

  public function actionUploadimage($id) {
    $model = $this->findModel($id);
    $file = array_pop($_FILES);

    if (isset($file['tmp_name'])) {
      if (getimagesize($file['tmp_name'])) {
        rename($file['tmp_name'], $file['tmp_name'] . $file['name']);
        $model->attachImage($file['tmp_name'] . $file['name']);
        return true;
      }
    }

    return false;
  }

  /**
   * Deletes an existing Product model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }

  /**
   * Finds the Product model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Product the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = Product::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  public function actionAddtocart($id) {
    $cart = new ShoppingCart();

    $model = Product::findOne($id);

    if ($model) {
      $cart->put($model, 1);
      return $this->redirect(['view', 'id' => $model->id]);
    }

    throw new NotFoundHttpException();
  }

  public function actionBuyitnow($id) {
    $cart = new ShoppingCart();

    $model = Product::findOne($id);

    if ($model) {
      $cart->put($model, 1);
      return $this->redirect(['cart/view']);
    }

    throw new NotFoundHttpException();
  }
}

frontend/views/category/_product_filter.php
<?php
  use app\models\Cut;
  use app\models\Material;
  use yii\helpers\ArrayHelper;
  use yii\helpers\Url;
  use yii\widgets\ActiveForm;

  $js = <<<JS

  window.resetform = function() {
    var Form = $('#myForm');
    $('select', Form).each(function() { this.selectedIndex = 0 });
    $("button", Form).click();
  }
JS;
  $this->registerJs($js);
?>

<div class="product-filter">
  <?php $form = ActiveForm::begin([
      'id'      => 'myForm',
      'method'  => 'get',
      'action'  => Url::to(['category/view', 'id' => $filter->category_id]),
      'options' => [
        'data-pjax' => true,
        'enctype'   => 'multipart/form-data',
        'onchange'  => '$("button", this).click()',
      ]]);
    echo $form->field($filter, 'price_to')->dropDownList(
      $filter->pricesTo(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Price to'))
    . $form->field($filter, 'cut')->dropDownList(
      ArrayHelper::map(Cut::all(), 'id', Yii::t('site', 'description_en')),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Cut'))
    . $form->field($filter, 'material')->dropDownList(
      ArrayHelper::map(Material::all(), 'id', Yii::t('site', 'description_en')),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Material'))
    . $form->field($filter, 'moisture')->dropDownList(
      [
        '1' => Yii::t('site', 'Natural'),
        '2' => Yii::t('site', 'Dry') . ' (<9%)',
      ],
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Moisture'))
    . '<div onclick="window.resetform()" class="btn btn-default">Сбросить</div><br>'
    . $form->field($filter, 'length_from')->dropDownList(
      $filter->lengthsFrom(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Length from'))
    . $form->field($filter, 'length_to')->dropDownList(
      $filter->lengthsTo(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Length to'))
    . $form->field($filter, 'width_from')->dropDownList(
      $filter->widthsFrom(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Width from'))
    . $form->field($filter, 'width_to')->dropDownList(
      $filter->widthsTo(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Width to'))

    . $form->field($filter, 'thickness')->dropDownList(
      $filter->thicknesses(),
      ['prompt' => Yii::t('site', 'Select') . '...'])
      ->label(Yii::t('site', 'Thickness'))

    ;
    echo '<button type="submit" style="display:none;"></button>';
    ActiveForm::end();
  ?>
</div>
<style>
.product-filter .form-group {
  display: inline-block;
  width: 18%;
  margin-right: 2%;
}

</style>

frontend/views/category/view.php
<?php
  use yii\grid\GridView;
  use yii\helpers\Html;
  use yii\widgets\ListView;
  use yii\widgets\Pjax;

  /* @var $this yii\web\View */
  /* @var $model app\models\Category */

  $this->title = $model->{Yii::t('site', 'description_en')};
  $this->params['breadcrumbs'][] = ['label' => Yii::t('site', 'Catalog'), 'url' => ['site/catalog']];

  //$this->params['breadcrumbs'][] = $this->title;
  if (count($categories) > 1) {
    $this->params['secondary_nav_items'] = $categories;
  }

  //print_r($categories);
?>

<?php Pjax::begin();?>
<?=$this->render('_product_filter.php', ['filter' => $filter])?>


<?=ListView::widget([
  'dataProvider' => $products,
  'layout'       => '{items}',
  'itemView'     => '/product/category_preview',
  'itemOptions'  => ['tag' => false],
  'options'      => ['class' => 'clearfix category-view'],
]);?>
<?php Pjax::end();?>


<?php

if (!Yii::$app->user->isGuest): ?>

  <p>
    <?=Html::a(Yii::t('app', 'Добавить товар'), ['product/create', 'category_id' => $model->id], ['class' => 'btn btn-primary', 'data-method' => 'post'])?>
    <?=Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary'])?>
    <?=Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
  'class' => 'btn btn-danger',
  'data'  => [
    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
    'method'  => 'post',
  ],
])?>
  </p>

  <?=GridView::widget([
  'dataProvider' => $products,
  'columns'      => [
    ['class' => 'yii\grid\SerialColumn'],
    //'id',
    [
      'label'  => 'Images',
      'format' => 'html',
      'value'  => function ($model) {return '<img src="' . $model->getImage()->getPath('150x150', ['abs' => true]) . '"/>';},
    ],
    'model' . Yii::t('site', '_en'),
    'sku' . Yii::t('site', '_en'),
    [
      'label' => 'Category',
      'value' => 'category.description' . Yii::t('site', '_en'),
    ],
    'price',
    // 'quantity',
    'length',
    // 'height',
    // 'sort_order',

    [
      'class'      => 'yii\grid\ActionColumn',
      'controller' => 'product',
    ],
  ],
]);?>
<?php endif;?>