frontend/controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\data\ArrayDataProvider;
use app\models\Order;
use app\models\Product;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yz\shoppingcart\ShoppingCart;
use app\models\CheckoutForm;

class CartController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	public function actionView()
	{
		$cart = new ShoppingCart();
		$positionsDataProvider = new ArrayDataProvider([
			'allModels' => $cart->positions,
			'key' => 'id',
			'pagination' => [
				'pageSize' => 0,
			],
		]);
		
		$form = new CheckoutForm();
		
		if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			$order = new Order();
			$attributes = $form->getAttributes();
			$attributes['cart'] = $cart->getSerialized();
			$order->setAttributes($attributes);
			if ($order->save()) {
				$this->sendReportEmail($cart, $order);
				if ($form->payment_method == 'cash'){
					return $this->redirect(['success'] + $order->getAttributes(['id', 'firstname']));
				}
			}			
		}

		return $this->render('view',[
			'cart' => $cart,
			'positionsDataProvider' => $positionsDataProvider,
			'cform' => $form,
		]);
	}

	public function actionSuccess()
	{
		$cart = new ShoppingCart();
		$cart->removeAll();
		
		$order_id = Yii::$app->request->get('id');
		$firstname = Yii::$app->request->get('firstname');

		return $this->render('success',[
			'order_id' => $order_id,
			'firstname' => $firstname,
		]);
	}

	public function actionRemoveall()
	{
		$cart = new ShoppingCart();
		$cart->removeAll();		
		return $this->redirect('view');
	}

	public function actionUpdateposition($id, $q)
	{
		$cart = new ShoppingCart();
		$model = Product::findOne($id);
		$cart->update($model, $q);	
		return $this->redirect('/cart/view');
	}
	
	protected function sendSuccessEmail($cart, $order)
	{
		Yii::$app->mailer->compose()
		    ->setFrom('info@les-furniture.ru')
		    ->setTo($order->getAttribute('email'))
		    ->setSubject('Подтверждение заказа ' .$order->getAttribute('id'))
		    ->setTextBody('Plain text content')
		    ->send();		
		
	}
	
	protected function sendReportEmail($cart, $order)
	{
		$i = 1;
		$text = '';
		foreach ($cart->getPositions() as $p){
			$text .= $i .'. ' .$p->getAttribute('model_ru') .'. Количество: ' .$p->getQuantity() .PHP_EOL
			.Url::to(['product/view', 'id' => $p->getAttribute('id')], true) .PHP_EOL;
			$i++;
		}
		$text .= 'Итого: ' .$cart->getCost() .' руб.';
		
		Yii::$app->mailer->compose()
		    ->setFrom('order@les-furniture.ru')
		    ->setTo('info@les-furniture.ru')
		    ->setSubject('Получен новый заказ №'.$order->getAttribute('id'))
		    ->setTextBody('Имя клиента: ' .$order->getAttribute('firstname') .PHP_EOL 
			    .'Телефон клиента: ' .$order->getAttribute('phone') .PHP_EOL
			    .'E-mail клиента: ' .$order->getAttribute('email') .PHP_EOL
			    .'Способ оплаты: ' .$order->getAttribute('payment_method') .PHP_EOL .$text
		    )
		    ->send();		
		
	}
}

frontend/views/cart/productQuantity.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yz\shoppingcart\ShoppingCart;
use yii\jui\Spinner;

$cart = new ShoppingCart();
$id = $model->id;
$updatePositionUrl = Url::to(['cart/updateposition']);
?>

<?= Spinner::widget([
	'id' => 'quantity' .$id,
    'name'  => 'quantity',
    'value' => $model->getQuantity(),
    'options' => [
	    'style' => 'width: 2em;',
	    'readonly' => 'true',
    ],
    'clientOptions' => [
	    'step' => 1,
	    'min' => 0,
	    'numberFormat' => 'n',
    ],
    'clientEvents' => [
	    'stop' => 'function () {
		    if ($(this).val() == ' .$model->getQuantity() .') {
			    $("#updatePosition' .$id .'").addClass("hidden");
		    } else {
			    $("#updatePosition' .$id .'").removeClass("hidden");
		    }
	    }',
    ],
]) ?>
<a id="updatePosition<?= $id ?>" href="#" class="hidden" onclick="updatePosition(<?= $id ?>)"><span class="glyphicon glyphicon-ok"></span></a>
<script>
	function updatePosition(id) {
		$.get('<?= Url::to(['cart/updateposition'])?>', {
			id: id,
			q: $('#quantity' + id).val()
		});
	}
</script>

frontend/views/cart/success.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yz\shoppingcart\ShoppingCart;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('site', 'Cart');
$this->params['breadcrumbs'][] = $this->title;

$message = [
	'ru' => 'Уважаемый ' .$firstname .', Ваш заказ был успешно размещен, наш менеджер свяжется с вами ближайшее время.',
	'en' => 'Dear ' .$firstname .', your order has been placed. Our manager will contact you ASAP.',
];
//!  Ниже ссылка на каталог и контакты
?>
<div class="cart-success">
	<h1>Успешно</h1>
	<p> Номер заказа: <?= $order_id ?> </p>
	<p><?= $message[Yii::$app->language]?></p>
	
</div>

frontend/views/cart/view.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yz\shoppingcart\ShoppingCart;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('site', 'Cart');
$this->params['breadcrumbs'][] = $this->title;
Yii::$app->formatter->thousandSeparator = ' ';
?>
<div class="site-about">
	<h1 class="text-uppercase letter-spacing-medium"><?= Html::encode($this->title) ?></h1>
	
	<?= GridView::widget([
		'dataProvider' => $positionsDataProvider,
		'options' => [
			'class' => 'les-cart',
		],
		'tableOptions' => [
			'class' => 'table text-center',
		],
		'headerRowOptions' => [
			'class' => 'text-uppercase font-normal letter-spacing-medium',
		],
		'rowOptions' => [
			'class' => 'text-grey',
		],
		'showFooter' => true,
		'summary' => false,
		'columns' => [
/*
			[
				'header' => false,
				'class' => 'yii\grid\SerialColumn',
				'footer' => Yii::t('site', 'Total'),
			],
*/
			[
				'label' => Yii::t('site', 'Item'),
				'format' => 'html',
				'value' => function($model){ return '<img src="' .$model->getImage()->getPath('150x150', ['fit' => true, 'abs' => true]) .'"/>'; },
				'footer' => Html::a(Yii::t('site', 'Clear cart'), ['cart/removeall'], ['class' => 'xsmall pull-left']),
			],
			[
				'label' => Yii::t('site', 'Model'),
				'value' => function($model){ return $model->{Yii::t('site', 'model_en')}; },
			],
			[
				'label' => Yii::t('site', 'QTY'),
				'format' => 'raw',
				'value' => function($model){ return $this->render('/cart/productQuantity', [
					'p_img' => $model->getImage(),
					'model' => $model,
					]); },
			],
			[
				'label' => Yii::t('site', 'Unit price'),
				'value' => function($model){ return Yii::$app->formatter->asDecimal($model->price); },
			],
			[
				'label' => Yii::t('site', 'Cost'),
				'value' => function($model){ return Yii::$app->formatter->asDecimal($model->price * $model->getQuantity()); },
				'footer' => Yii::t('site', 'Total') .': ' .Yii::$app->formatter->asDecimal($cart->getCost()),
			],
//			 ['class' => 'yii\grid\ActionColumn'],
		],
	]); ?>
		
<?php if($cart->getCount()) : ?>
	<div class="row col-xs-offset">
		<div id="checkout-form" class="product-form">
			
			<?php $form = ActiveForm::begin(['options' => [],'layout' => 'inline']); ?>
		
			<?= $form->field($cform, 'firstname', [
					'template' => '{input}',
					'options' => [
						'class' => 'col-xs-4',
					],
				])->textInput([
					'placeholder' => Yii::t('site', 'Name'),
					'class' => 'form-control col-xs-12',
				]) ?>
		
			<?= $form->field($cform, 'phone', [
					'template' => '{input}',
					'options' => [
						'class' => 'col-xs-4',
					],
				])->widget(\yii\widgets\MaskedInput::className(), [
			    'mask' => '+7 (999) 999-9999',
			    'options' => [
				    'placeholder' => Yii::t('site', 'Phone'),
					'class' => "form-control col-xs-12",
			    ],
			]) ?>
		
			<?= $form->field($cform, 'email', [
					'template' => '{input}',
					'options' => [
						'class' => 'col-xs-4',
					],
				])->textInput([
					'placeholder' => Yii::t('site', 'E-mail'),
					'class' => "form-control col-xs-12",
				]) ?>
		
<!-- 			<?= $form->field($cform, 'payment_method')->inline()->radioList(['cash' => 'НАЛ', 'wire' => 'ОБНАЛ', 'card' => 'МАСТЕРКАРД']) ?> -->
			
			<div class="col-xs-12 form-group text-center space-top-small">
                <?= Html::submitButton(Yii::t('site', 'Make order'), ['class' => 'les-button', 'name' => 'contact-button']) ?>
			</div>
		
			<?php ActiveForm::end(); ?>
		
		</div>
	</div>
<?php endif; ?>

</div>